### ISSUE TITLE
sbt.ResolveException: unresolved dependency: commons-logging#commons-logging

### ISSUE THREAD

**Issue by svenmueller** [sphereio/commercetools-sunrise-java#366]
Any idea why i get this error when running `./sbt test`?

```bash
smueller@Miami-2 ~/dev/src/commercetools-sunrise-java $ ./sbt test
[info] Loading project definition from /Users/smueller/dev/src/commercetools-sunrise-java/project
[info] Set current project to commercetools-sunrise (in build file:/Users/smueller/dev/src/commercetools-sunrise-java/)
[info] Updating {file:/Users/smueller/dev/src/commercetools-sunrise-java/}common...
[info] Resolving com.typesafe.play#twirl-api_2.11;1.1.1 ...
[info] Compiling 1 Java source to /Users/smueller/dev/src/commercetools-sunrise-java/sbt-tasks/target/scala-2.11/test-classes...
[info] Resolving org.apache.commons#commons-lang3;3.4 ...
[info] Compiling 6 Java sources to /Users/smueller/dev/src/commercetools-sunrise-java/move-to-sdk/target/scala-2.11/test-classes...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Test run started
[info] Test tasks.WebjarsFilesCopierTest.copiesMultipleFiles started
[info] Test run started
[info] Resolving org.assertj#assertj-core;3.0.0 ...
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.emptyWhenNotConfigured started
[info] Test tasks.WebjarsFilesCopierTest.copiesFile started
[info] Test tasks.WebjarsFilesCopierTest.copiesFileFromAJarPackage started
[info] Test tasks.WebjarsFilesCopierTest.failsSilentlyOnInvalidFile started
[info] Test tasks.WebjarsFilesCopierTest.copiesFileWithNonExistingDirectory started
[info] Test tasks.WebjarsFilesCopierTest.copiesFileWithExistingDirectory started
[info] Test run finished: 0 failed, 0 ignored, 6 total, 0.781s
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.discardsWithEmptyCategoryTree started
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.worksWithEmptyFacetOptions started
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.discardsOnMissingLocale started
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.discardsEmptyBranches started
[info] Passed: Total 6, Failed 0, Errors 0, Passed 6
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.keepsOrderFromCategoryTree started
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.inheritsInformationFromLeaves started
[info] Test io.sphere.sdk.facets.CategoryTreeFacetOptionMapperTest.replacesIdForName started
[info] Test run finished: 0 failed, 0 ignored, 8 total, 0.778s
[info] Test run started
[info] Test io.sphere.sdk.facets.SelectFacetTest.optionsListIsTruncatedIfOverLimit started
[info] Test io.sphere.sdk.facets.SelectFacetTest.optionsListIsNotTruncatedIfBelowLimit started
[info] Test io.sphere.sdk.facets.SelectFacetTest.doesNotFilter started
[info] Test io.sphere.sdk.facets.SelectFacetTest.canBeDisplayedIfOverThreshold started
[info] Test io.sphere.sdk.facets.SelectFacetTest.canNotBeDisplayedIfBelowThreshold started
[info] Test io.sphere.sdk.facets.SelectFacetTest.filtersByAnyFilterValues started
[info] Test io.sphere.sdk.facets.SelectFacetTest.throwsExceptionOnWrongThresholdAndLimit started
[info] Test io.sphere.sdk.facets.SelectFacetTest.filtersByAllFilterValues started
[info] Test run finished: 0 failed, 0 ignored, 8 total, 0.049s
[info] Test run started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstanceWithDifferentSelected started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstanceWithDifferentChildren started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstance started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstanceWithDifferentCount started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstanceWithDifferentValue started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstanceFromTermStatsWithUnselectedValue started
[info] Test io.sphere.sdk.facets.FacetOptionTest.createsInstanceFromTermStats started
[info] Test run finished: 0 failed, 0 ignored, 7 total, 0.012s
[info] Test run started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.sortsOptionsAsGivenList started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.comparisonEnsuresTransitiveRelation started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.onEmptyListKeepsSameOrder started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.worksWithEmptyFacetOptions started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.comparisonEnsuresSymmetricRelation started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.givenUnsortedFacetOptionsAreNotSorted started
[info] Test io.sphere.sdk.facets.CustomSortedFacetOptionMapperTest.leavesUnknownOptionsAtTheEnd started
[info] Test run finished: 0 failed, 0 ignored, 7 total, 0.011s
[info] Test run started
[info] Test io.sphere.sdk.facets.SelectFacetBuilderTest.mapsOptions started
[info] Test io.sphere.sdk.facets.SelectFacetBuilderTest.createsInstanceWithOptionalValues started
[info] Test io.sphere.sdk.facets.SelectFacetBuilderTest.createsInstance started
[info] Test io.sphere.sdk.facets.SelectFacetBuilderTest.createsInstanceWithDifferentFacetResult started
[info] Resolving oauth.signpost#signpost-commonshttp4;1.2.1.2 ...
[info] Test run finished: 0 failed, 0 ignored, 4 total, 0.235s
[info] Test run started
[info] Test io.sphere.sdk.play.metrics.MetricHttpClientTest.executesRequestWithNoContext started
[info] Test io.sphere.sdk.play.metrics.MetricHttpClientTest.executesRequestWithContext started
[info] Test io.sphere.sdk.play.metrics.MetricHttpClientTest.reportsMetricsWithContext started
[info] Test run finished: 0 failed, 0 ignored, 3 total, 0.026s
[info] Passed: Total 37, Failed 0, Errors 0, Passed 37
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: commons-logging#commons-logging;1.1.1: configuration not found in commons-logging#commons-logging;1.1.1: 'master(compile)'. Missing configuration: 'compile'. It was required from commons-beanutils#commons-beanutils;1.9.2 compile
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		commons-logging:commons-logging:1.1.1
[warn] 		  +- commons-beanutils:commons-beanutils:1.9.2 (/Users/smueller/dev/src/commercetools-sunrise-java/build.sbt#L117)
[warn] 		  +- common:common_2.11:0.7.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: commons-logging#commons-logging;1.1.1: configuration not found in commons-logging#commons-logging;1.1.1: 'master(compile)'. Missing configuration: 'compile'. It was required from commons-beanutils#commons-beanutils;1.9.2 compile
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (common/*:update) sbt.ResolveException: unresolved dependency: commons-logging#commons-logging;1.1.1: configuration not found in commons-logging#commons-logging;1.1.1: 'master(compile)'. Missing configuration: 'compile'. It was required from commons-beanutils#commons-beanutils;1.9.2 compile
[error] Total time: 5 s, completed 02.05.2016 22:31:28
```

**Comment by schleichardt** [comment]
cannot reproduce.

Sometimes this kind of error happens with corrupt files/configs in `~/.ivy2` or in the public repo. 
Deleting `~/.ivy2` folder might help.
If that does not work we could overwrite the logging dependency to a newer version.

**Comment by svenmueller** [comment]
Thx, clearing the `.ivy2/` folder did indeed help in my case.

**Comment by satishbanka** [comment]
My error is not getting resolved after deleting the folder ~/.ivy2.
scalaVersion := "2.11.8"
I have deleted the .ivy2 and rebuild the project using "sbt package". It has re-downloaded all the packages. However the error is still not resolved.

Can someone advise on this pls.

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: commons-codec#commons-codec;1.9: not found, unresolved dependency: com.fasterxml.jackson.core#jackson-annotations;2.6.0: not found, download failed: commons-logging#commons-logging;1.1.3!commons-logging.jar]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1204)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:304)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "/usr/hdp/current/spark2-client/python/pyspark/shell.py", line 38, in <module>
    SparkContext._ensure_initialized()
  File "/usr/hdp/current/spark2-client/python/pyspark/context.py", line 293, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/hdp/current/spark2-client/python/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number

**Comment by anigos** [comment]
Hey any update about this error. For my case also even a fresh empty project throwing the same error.

**Comment by kevinkurek** [comment]
I had an unresolved dependency issue with spark so I added this to my build.sbt:
`libraryDependencies += "org.apache.commons" % "commons-compress" % "1.18"`

After I committed, pushed, and checked TravisCI the tests all passed. Hope this helps someone else.
